// apps/anime.joulev.dev/src/lib/components/card/publicCard.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import { convertSeason, transition } from "$lib/utils";
  import Base from "./base.svelte";
  import Score from "$lib/components/score.svelte";
  import type { CardVariant, ListItem } from "$lib";

  export let item: ListItem;
  export let variant: CardVariant;

  let showDetailedScore = false;
  const onHover = () => (showDetailedScore = true);
  const onLeave = () => (showDetailedScore = false);
</script>

<Base {item} {variant}>
  <div
    class="flex flex-row justify-between items-end"
    on:mouseover={onHover}
    on:focus={onHover}
    on:mouseleave={onLeave}
    on:blur={onLeave}
  >
    {#if showDetailedScore && item.score}
      <div class="flex flex-row help-text" in:fade={transition}>
        {#each Object.entries(item.advancedScores) as [key, score], i}
          <div
            class="group {i > 0 && 'ml-3 border-l border-main-300 dark:border-main-700 pl-3'}"
            title={key}
          >
            <span class="hidden md:inline-block lg:hidden xl:inline-block">{key}</span>
            <span class="hidden lg:inline-block xl:hidden">{key.substring(0, 3)}</span>
            {score}
          </div>
        {/each}
      </div>
    {:else}
      <div class="flex flex-row help-text" in:fade={transition}>
        <div>
          {#if item.media?.season && item.media?.seasonYear}
            {convertSeason(item.media.season)} {item.media.seasonYear}
          {:else}
            Season N/A
          {/if}
        </div>
        {#if item.repeat}
          <div class="ml-3 border-l border-main-300 dark:border-main-700 pl-3">
            &times;{item.repeat + 1}
          </div>
        {/if}
      </div>
    {/if}
    {#if (variant === "watching" || variant === "rewatching") && item.progress}
      <div class="text-sm">Episode {item.progress}/{item.media?.episodes ?? "unknown"}</div>
    {:else if item.score}
      <div class="flex flex-row gap-3 items-center">
        <Score score={item.score} />
        <div>{item.score}</div>
      </div>
    {:else}
      <div class="help-text">
        Last updated: {item.updatedAt
          ? new Date(item.updatedAt * 1000).toLocaleDateString("en-gb")
          : "N/A"}
      </div>
    {/if}
  </div>
</Base>

// apps/anime/app/_card/public-card.tsx
"use client";

import clsx from "clsx";
import { useState } from "react";

import { Item } from "~/lib/get-lists";
import { convertSeason } from "~/lib/utils";

import Base from "./base";
import { CardVariant } from "./card";

function BottomRightInfo({ item, variant }: { item: Item; variant: CardVariant }) {
  if ((variant === "watching" || variant === "rewatching") && item.progress)
    return (
      <div className="text-sm">
        Episode {item.progress}/{item.media?.episodes ?? "unknown"}
      </div>
    );

  if (item.score)
    return (
      <div className="flex flex-row gap-3 items-center">
        {/* <Score score={item.score} /> */}Score
        <div>{item.score}</div>
      </div>
    );

  return (
    <div className="help-text">
      Last updated:{" "}
      {item.updatedAt ? new Date(item.updatedAt * 1000).toLocaleDateString("en-gb") : "N/A"}
    </div>
  );
}

export default function PublicCard({ item, variant }: { item: Item; variant: CardVariant }) {
  const [showDetailedScore, setShowDetailedScore] = useState(false);
  const onHover = () => setShowDetailedScore(true);
  const onLeave = () => setShowDetailedScore(false);

  return (
    <Base item={item} variant={variant}>
      <div
        className="flex flex-row justify-between items-end"
        onMouseOver={onHover}
        onFocus={onHover}
        onMouseLeave={onLeave}
        onBlur={onLeave}
      >
        {showDetailedScore && item.score ? (
          <div className="flex flex-row help-text">
            {Object.entries(item.advancedScores).map(([key, score]: [string, any], i) => (
              <div
                key={i}
                className={clsx("group", i > 0 && "ml-3 border-l border-daw-main-300 pl-3")}
              >
                <div title={`${key}: ${score}/10`}>
                  <span className="hidden md:inline-block lg:hidden xl:inline-block">{key}</span>
                  <span className="hidden lg:inline-block xl:hidden">
                    {key.substring(0, 3)}
                  </span>{" "}
                  {score}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="flex flex-row help-text">
            <div>
              {item.media?.season && item.media?.seasonYear
                ? `${convertSeason(item.media.season)} ${item.media.seasonYear}`
                : "Season N/A"}
            </div>
            {item.repeat ? (
              <div className="ml-3 border-l border-daw-main-300 pl-3">&times;{item.repeat + 1}</div>
            ) : null}
          </div>
        )}
        <BottomRightInfo item={item} variant={variant} />
      </div>
    </Base>
  );
}
