// apps/anime/app/_card/base.tsx
import clsx from "clsx";
import Image from "next/image";

import { Item } from "~/lib/get-lists";
import { getTitle } from "~/lib/utils";
import { CardVariant } from "./card";

export default function Base({
  item,
  variant,
  children,
}: React.PropsWithChildren<{ item: Item; variant: CardVariant }>) {
  return (
    <div className="card flex flex-col relative">
      {/* <div className="absolute top-6 right-6 flex flex-row gap-1.5">
    Top right buttons for mutations
  </div> */}
      <div className="p-6 flex flex-row gap-6">
        {item.media?.coverImage?.medium ? (
          <div className="hidden sm:block w-18 min-h-[96px] rounded shrink-0 overflow-hidden relative">
            <Image src={item.media.coverImage.medium} alt="cover" fill className="object-cover" />
          </div>
        ) : (
          <div className="hidden sm:block w-18 min-h-[96px] rounded shrink-0 bg-daw-main-200" />
        )}
        <div
          className={clsx(
            "flex-1 flex min-w-0 flex-col justify-between gap-6",
            item.score && "sm:gap-1.5",
          )}
        >
          <div className="flex flex-col">
            <div className="text-lg">
              <a className="anchor" href={`https://anilist.co/anime/${item.mediaId}`}>
                {getTitle(item.media?.title)}
              </a>
            </div>
            <div className="help-text">{item.media?.title?.native ?? "Japanese title N/A"}</div>
          </div>
          {children}
        </div>
      </div>
      {variant !== "planning" && variant !== "completed" && variant !== "completed-others" && (
        <div
          className={clsx(
            "h-1 rounded-r",
            variant === "watching" && "bg-green",
            variant === "rewatching" && "bg-blue",
            variant === "paused" && "bg-yellow",
            variant === "dropped" && "bg-red",
          )}
          style={{
            width: `${
              (100 * (item.progress ?? 0)) / (item.media?.episodes ?? item.progress ?? 1)
            }%`,
          }}
        />
      )}
    </div>
  );
}

// apps/anime.joulev.dev/src/lib/components/card/base.svelte
<script lang="ts">
  import { tweened } from "svelte/motion";
  import { getTitle, longTransition } from "$lib/utils";
  import A from "$lib/components/a.svelte";
  import type { CardVariant, ListItem } from "$lib";
  export let item: ListItem;
  export let variant: CardVariant;

  const progressPercentage = tweened(0, longTransition);
  $: progressPercentage.set(
    (100 * (item.progress ?? 0)) / (item.media?.episodes ?? item.progress ?? 1),
  );
</script>

<div class="flex flex-col rounded-lg overflow-hidden bg-main-200 dark:bg-main-800 relative">
  <div class="absolute top-6 right-6 flex flex-row gap-1.5">
    <slot name="top-right" />
  </div>
  <div class="p-6 flex flex-row gap-6">
    {#if item.media?.coverImage?.medium}
      <img
        src={item.media.coverImage.medium}
        alt="cover"
        class="hidden sm:block w-18 min-h-[96px] rounded-lg shrink-0 object-cover"
      />
    {:else}
      <div
        class="hidden sm:block w-18 min-h-[96px] rounded-lg shrink-0 bg-main-300 dark:bg-main-700"
      />
    {/if}
    <div class="flex-1 flex min-w-0 flex-col justify-between gap-6 {item.score && 'sm:gap-1.5'}">
      <div class="flex flex-col">
        <div class="text-lg">
          <A href={`https://anilist.co/anime/${item.mediaId}`}>
            {getTitle(item.media?.title)}
          </A>
        </div>
        <div class="help-text">
          {item.media?.title?.native ?? "Japanese title N/A"}
        </div>
      </div>
      <slot />
    </div>
  </div>
  {#if variant !== "planning" && variant !== "completed" && variant !== "completed-others"}
    <div
      class="h-1 rounded-full"
      class:bg-green={variant === "watching"}
      class:bg-blue={variant === "rewatching"}
      class:bg-yellow={variant === "paused"}
      class:bg-red={variant === "dropped"}
      style="width: {$progressPercentage}%;"
    />
  {/if}
</div>
