// apps/anime.joulev.dev/src/routes/auth/+page.svelte
<script>
  import { dev } from "$app/environment";
  import Button from "$lib/components/button.svelte";
  import Loading from "$lib/components/loading.svelte";
  import { auth } from "$lib/stores/user";

  const clientId = dev ? 9330 : 9619;
</script>

{#if $auth.loading}
  <Loading />
{:else if $auth.token === ""}
  <p>
    If you are AniList user @joulev (aka me) and would like to make change to the lists using this
    interface, please log in below. You will be directed to AniList to complete the authentication
    process. Do note that you will be refused access if you log in with a different AniList account.
  </p>
  <p>
    I do not plan to expand this site for other users, as I do not intend to build a full-fledged
    AniList client.
  </p>
  <Button
    href="https://anilist.co/api/v2/oauth/authorize?client_id={clientId}&response_type=token"
    notExternal
  >
    Log in with AniList
  </Button>
{:else}
  <p>You are authenticated. Hi to myself!</p>
{/if}

// apps/anime/app/auth/page.tsx
import { getToken } from "~/lib/auth";

export default function Page() {
  const token = getToken();
  const clientId = process.env.CLIENT_ID;
  const origin = process.env.ORIGIN;
  if (token) return <p>You are authenticated. Hi to myself!</p>;
  return (
    <>
      <p>
        If you are AniList user @joulev (aka me) and would like to make change to the lists using
        this interface, please log in below. You will be directed to AniList to complete the
        authentication process. Do note that you will be refused access if you log in with a
        different AniList account.
      </p>
      <p>
        I do not plan to expand this site for other users, as I do not intend to build a
        full-fledged AniList client.
      </p>
      <a
        href={`https://anilist.co/api/v2/oauth/authorize?client_id=${clientId}&redirect_uri=${origin}/auth/callback&response_type=code`}
        className="btn btn-primary"
      >
        Log in with AniList
      </a>
    </>
  );
}

export const dynamic = "force-dynamic";
