// apps/anime/app/_card/card.tsx
import { getToken } from "~/lib/auth";
import { Item } from "~/lib/get-lists";
import PublicCard from "./public-card";
import PrivateCard from "./private-card";

export type CardVariant =
  | "watching"
  | "rewatching"
  | "completed"
  | "completed-others"
  | "paused"
  | "dropped"
  | "planning";

export default function Card({ item, variant }: { item: Item; variant: CardVariant }) {
  const token = getToken();
  const Component = token ? PrivateCard : PublicCard;
  return <Component item={item} variant={variant} />;
}

// apps/anime-sveltekit/src/lib/components/card.svelte
<script lang="ts">
  import { auth } from "$lib/stores/user";
  import { onMount } from "svelte";
  import type { CardVariant, ListItem, SvelteComponent } from "$lib";
  export let item: ListItem;
  export let variant: CardVariant;

  let Component: SvelteComponent<{ item: ListItem; variant: CardVariant }>;
  onMount(() => {
    auth.subscribe(async state => {
      Component = state.loggedIn
        ? (await import("./card/privateCard.svelte")).default
        : (await import("./card/publicCard.svelte")).default;
    });
  });
</script>

<svelte:component this={Component} {item} {variant} />
